{{- if .Values.grafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki-stack.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "loki-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "loki-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      serviceAccountName: {{ include "loki-stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.grafana.podSecurityContext | nindent 8 }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          securityContext:
            {{- toYaml .Values.grafana.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/grafana
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: data
              mountPath: /var/lib/grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "loki-stack.fullname" . }}-grafana
                  key: admin-password
                  optional: true
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_AUTH_DISABLE_SIGNOUT_MENU
              value: "true"
      volumes:
        - name: config
          configMap:
            name: {{ include "loki-stack.fullname" . }}-grafana-config
        - name: dashboards
          configMap:
            name: {{ include "loki-stack.fullname" . }}-grafana-dashboards
        - name: data
          emptyDir: {}
{{- end }}