{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-stack.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    {{- include "loki-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      protocol: TCP
{{- end }}