{{- if .Values.loki.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki-stack.fullname" . }}-loki-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
data:
  loki.yaml: |
    auth_enabled: {{ .Values.loki.config.auth_enabled }}
    server:
      http_listen_port: {{ .Values.loki.config.server.http_listen_port }}
      grpc_listen_port: {{ .Values.loki.config.server.grpc_listen_port }}
      log_level: {{ .Values.loki.config.server.log_level }}
    common:
      path_prefix: {{ .Values.loki.config.common.path_prefix }}
      storage:
        filesystem:
          chunks_directory: {{ .Values.loki.config.common.storage.filesystem.chunks_directory }}
          rules_directory: {{ .Values.loki.config.common.storage.filesystem.rules_directory }}
      replication_factor: {{ .Values.loki.config.common.replication_factor }}
      ring:
        instance_addr: {{ .Values.loki.config.common.ring.instance_addr }}
        kvstore:
          store: {{ .Values.loki.config.common.ring.kvstore.store }}
    schema_config:
      configs:
        {{- toYaml .Values.loki.config.schema_config.configs | nindent 8 }}
    limits_config:
      {{- toYaml .Values.loki.config.limits_config | nindent 6 }}
    compactor:
      {{- toYaml .Values.loki.config.compactor | nindent 6 }}
    ingester:
      {{- toYaml .Values.loki.config.ingester | nindent 6 }}
{{- end }}