{{- if .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "loki-stack.fullname" . }}-quota
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}