{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | b64enc }}
  {{- end }}
  {{- range $key, $value := .Values.secret.additional }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}