{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-cd.fullname" . }}-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "argo-cd.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "argo-cd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: {{ .Values.server.service.name }}
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
    - name: {{ .Values.server.service.httpsName }}
      port: {{ .Values.server.service.httpsPort }}
      targetPort: {{ .Values.server.service.httpsTargetPort }}
      protocol: TCP
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: metrics
      port: 8083
      targetPort: 8083
      protocol: TCP
{{- end }}